# demo_setup.yml

- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars/aws_credentials.vault.yml

  tasks:
    - name: new vairable with date
      set_fact: rundate="{{lookup('pipe','date +%Y-%m-%d\ \%H:%M:%S')}}"

    - name: example using security group rule descriptions
      ec2_group:
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        name: "msp_example"
        description: sg with rule descriptions
        region: "{{ item }}"
        purge_tags: no
        tags:
           Purpose: To secure the demo environment
           Updated by Ansible: "{{ rundate }}"

# Inbound Rules
        rules:
          - proto: tcp
            ports:
            - 80
            - 443
            - 32768 - 65535
            cidr_ip: 0.0.0.0/0
            cidr_ipv6: ::/0
            rule_desc: inbound server

          - proto: tcp
            ports:
            - 22
            cidr_ip: 12.41.206.100/32
            rule_desc: SSH access - Work

          - proto: tcp
            ports:
            - 22
            cidr_ip: 45.30.81.56/32
            rule_desc: SSH access - Home

# Outbound Rules
        rules_egress:
          - proto: tcp
            ports:
            - 80
            - 443
            - 32768 - 65535
            cidr_ip: 0.0.0.0/0
            cidr_ipv6: ::/0
            rule_desc: outbound server

# AWS Regions to deploy Security Groups
      loop:
         - us-east-1
         - us-west-1
         - us-east-2
         - us-west-2
