- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars/aws_credentials.vault.yml

  tasks:
    - name: new vairable with date
      set_fact: 
        rundate="{{ lookup('pipe','date +%Y-%m-%d\ \%H:%M:%S') }}"
        server_types="['MySQL','Webserver','Proxy']"
        AWS_regions="['us-east-2']"
        AWS_zones="['a','b']"

    - name: Provision a set of instances
      ec2:
         aws_access_key: "{{ ec2_access_key }}"
         aws_secret_key: "{{ ec2_secret_key }}"
         key_name: Pedderland1
         group: ['webserver','ssh']
         instance_type: t2.micro
         image: "ami-04328208f4f0cf1fe"
         region: "{{ item.1 }}"
         zone: "{{ item.1 }}{{ item.2 }}"
         wait: true
         exact_count: "1"
         count_tag:
            Class: "{{ item.0 }}"
         instance_tags:
            Name: "{{ item.0 }}"
            Class: "{{ item.0 }}"
            Created_by_Ansible: "{{ rundate }}"
      register: ec2
      with_nested:
        - "{{ server_types }}"
        - "{{ AWS_regions }}"
        - "{{ AWS_zones }}"