# demo_setup.yml

- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars/aws_credentials.vault.yml

  tasks:
    - name: get public IP
      ipify_facts:
      register: public_ip

    - name: webserver security group
      ec2_group:
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        name: "webserver"
        description: allow http and https access
        region: "{{ item }}"
        purge_tags: no
        purge_rules: yes
        purge_rules_egress: yes
        tags:
           Purpose: To allow http and https access

# Inbound Rules
        rules:
          - proto: tcp
            ports:
            - 80
            - 443
            cidr_ip: 0.0.0.0/0
            cidr_ipv6: ::/0
            rule_desc: inbound server

# Outbound Rules
        rules_egress:
          - proto: tcp
            ports:
            - 80
            - 443
            cidr_ip: 0.0.0.0/0
            cidr_ipv6: ::/0
            rule_desc: outbound server

# AWS Regions to deploy Security Groups
      loop:
         - us-east-1
         - us-west-1
         - us-east-2
         - us-west-2

    - name: ssh security group
      ec2_group:
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        name: "ssh"
        description: allow ssh
        region: "{{ item }}"
        purge_tags: no
        purge_rules: yes
        purge_rules_egress: yes
        tags:
           Purpose: Allow SSH from specific IP ranges.

# Inbound Rules
        rules:
          - proto: tcp
            ports:
            - 22
            cidr_ip: "{{ ipify_public_ip}}/32"
            rule_desc: SSH access - Specific IP

          # - proto: tcp
          #   ports:
          #   - 22
          #   cidr_ip: 45.30.81.56/32
          #   rule_desc: SSH access - Home

# Outbound Rules
        rules_egress:
          - proto: tcp
            ports:
            - 22
            cidr_ip: "{{ ipify_public_ip}}/32"
            rule_desc: SSH access - Specific IP

          # - proto: tcp
          #   ports:
          #   - 22
          #   cidr_ip: 45.30.81.56/32
          #   rule_desc: SSH access - Home

# AWS Regions to deploy Security Groups
      loop:
         - us-east-1
         - us-west-1
         - us-east-2
         - us-west-2