# demo_setup.yml

- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars/aws_credentials.vault.yml

  tasks:
    - name: new vairable with date
      set_fact: rundate="{{lookup('pipe','date +%Y-%m-%d\ \%H:%M:%S')}}"

    - name: Provision a set of instances
      ec2:
         aws_access_key: "{{ec2_access_key}}"
         aws_secret_key: "{{ec2_secret_key}}"
         key_name: Pedderland1
         group: msp_example
#         placement_group: head_em_up_move_em_out
         instance_type: t2.micro
         image: "ami-0350c5670171b5391"
         region: us-east-2
         wait: true
         exact_count: "{{ item.count }}"
         count_tag:
            Name: "{{ item.name }}"
         instance_tags:
            Name: "{{ item.name }}"
            Created by Ansible: "{{ rundate }}"
      register: ec2
      loop:
        - { name: 'MySQL', count: '2'}
        - { name: 'Webserver', count: '2'}
        - { name: 'Proxy', count: '2'}

#    - name: Add all instance public IPs to host group
#      add_host: hostname={{ item.public_ip }} groups=ec2hosts
#      loop: "{{ ec2.instances }}"
#
#- hosts: ec2hosts
#  name: configuration play
#  user: ec2_user
#  gather_facts: true
#
#  tasks:
#
#     - name: Check NTP service
#       service: name=ntpd state=started
